language: java
install: true
script:
  - "./gradlew clean build"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    docker login --email=$HEROKU_USERNAME --username=$HEROKU_USERNAME --password=$HEROKU_AUTH_TOKEN registry.heroku.com;
    docker tag swsb/effitchallenge registry.heroku.com/effit-challenge/web;
    docker push registry.heroku.com/cool-quote-registration-system/web;
    fi