language: java
install: true
script:
  - "./gradlew clean build"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    echo "$HEROKU_AUTH_TOKEN" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com;
    docker build ./ops/webapp -t swsb/effitchallenge;
    docker tag swsb/effitchallenge registry.heroku.com/effit-challenge/web;
    docker push registry.heroku.com/effit-challenge/web;
#    export WEB_DOCKER_IMAGE_ID="$(docker inspect swsb/effitchallenge --format={{.Id}})";
#    ./heroku-release.sh;
    fi
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
  on:
    branch: prod
  app:
    prod: effit-challenge
  run:
    - release web
