name: Java CI - Prod

on:
  push:
    branches:
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build and push to heroku
        run: echo "${{ secrets.HEROKU_AUTH_TOKEN }}" | docker login --username="${{ secrets.HEROKU_USERNAME }}" --password-stdin registry.heroku.com;
      - run: docker build ./ops/webapp -t swsb/effitchallenge;
      - run: docker tag swsb/effitchallenge registry.heroku.com/effit-challenge/web;
      - run: docker push registry.heroku.com/effit-challenge/web;
      - run: ./heroku-release.sh;

